version: "3.9"
services:

  api_monitor:
    image: MoneyRobot:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PW=password
      - DB_NAME=garmin_api_state_db
      - AWS_PROFILE=default
      - API_URL=https://api.qa.fitpay.ninja/health
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - "db"
    networks:
      - moneyrobot

  db:
    image: database:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=moneyrobot
      - MYSQL_PASSWORD=CREAM
      - MYSQL_ROOT_PASSWORD=Password123!
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - moneyrobot


    healthcheck:
      test: ["mysqladmin" ,"ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  moneyrobot:
    external: false
    name: moneyrobot