[tool.poetry]
name = "moneyrobot"
version = "0.1.0"
description = ""
authors = ["Michael Dreisinger <mike.dreisinger95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.7"
flask-mysqldb = "^1.0.1"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
